name: "Despliegue en bucket S3 y tirando infraestructura con EC2"
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Select the deployment environment"
        options:
          - deploy-bucket

jobs:
  deploy-bucket:
    if: ${{ github.event.inputs.environment == 'deploy-bucket'}}
    runs-on: ubuntu-latest

    env:
      aws_region: us-east-1

    steps:
      - name: Ckeckout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.aws_region }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Terraform plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Upload terraform-state to S3
        run: aws s3 cp ./terraform/terraform.tfstate s3://jose-manuel-bucket-tfstate/terraform.tfstate